### ISSUE TITLE
Cannot set property 'selected' of undefined

### ISSUE THREAD

**Issue by maciejjankowski** [alalonde/angular-multi-select#2]
Hello,
I tried using the directive in my app and I get the above error when I select an item.

here is the stack trace:

```
TypeError: Cannot set property 'selected' of undefined
    at setter (http://localhost:8081/xx/js/angular.js:10081:12)
    at extend.assign (http://localhost:8081/xx/js/angular.js:9922:16)
    at $setViewValue (http://localhost:8081/xx/js/angular.js:16554:7)
    at http://localhost:8081/xx/js/angular.js:16097:12
    at Scope.$eval (http://localhost:8081/xx/js/angular.js:11697:28)
    at Scope.$apply (http://localhost:8081/xx/js/angular.js:11797:23)
    at Scope.$delegate.__proto__.$apply (<anonymous>:864:30)
    at HTMLInputElement.<anonymous> (http://localhost:8081/xx/js/angular.js:16096:11)
    at HTMLInputElement.x.event.dispatch (http://code.jquery.com/jquery-1.10.2.min.js:5:14129)
    at HTMLInputElement.v.handle (http://code.jquery.com/jquery-1.10.2.min.js:5:10873) angular.js:9199
(anonymous function) angular.js:9199
(anonymous function) angular.js:6752
Scope.$apply angular.js:11799
$delegate.__proto__.$apply VM20301:864
(anonymous function) angular.js:16096
x.event.dispatch jquery-1.10.2.min.js:5
v.handle
```

I'm using Angular 1.2.4

`<multi-select ng-model="ruleset.sharedRuleList" available="rules" selected-label="Current rules" available-label="Available rules" display="r as r.domain_data"></multi-select>`

**Comment by alalonde** [comment]
Hi, this may have to do with the data in 'ruleset.sharedRuleList' and 'rules'.  The arrays should contain the same instances of objects.  When they are compared to see which items are selected, the == operator is used.  If you post a link to a fiddle or plunkr with all your code I could give more complete feedback.

**Comment by alalonde** [comment]
I just experienced this myself -- it appeared when the data in 'available' ('rules' in your case) was a promise that had already been resolved.  I applied a fix -- please let me know if your issue isn't resolved.

**Comment by stumpdk** [comment]
I get the same error with the newest version of the directive (which is great by the way!).

If I skip the $q part and use static data, there is no problems.

With a controller looking like this:

//Controller
app.controller('AdminstoragesUsergroupsCtrl', ['$scope', 'storagesUsergroupsService', function($scope, storagesUsergroupsService){
    //Available users
    $scope.availableUsergroups = {};

```
//Current storage
$scope.storage = {};
$scope.storage.usergroups = [{name: "test", name: "test"}];

//Loading available users
$scope.getAvailableUsers = function(){
    storagesUsergroupsService.loadAvailableUsergroups().then(function(data){
        $scope.availableUsergroups = data;
    })
};

$scope.getUsersForstorage = function(id){
    storagesUsergroupsService.loadstorageUsergroups(id).then(function(data){
        $scope.storage.usergroups = data;
    });
};

$scope.savestorageUserGroups = function(){
    storagesUsergroupsService.savestorageUserGroups().then(function(data){
        $scope.storage.usergroups = data;
    });
};

$scope.selectConfig = {
    requiredMin: 1,
    selectAll: true
};

//Loading data at init
$scope.getAvailableUsers();
$scope.getUsersForstorage();
```

}]);
