### ISSUE TITLE
Not working with Service/Promise

### ISSUE THREAD

**Issue by Chalkin** [alalonde/angular-multi-select#9]
I tried to get it working with a Service which get's the roles from the backend. But i can't get it working.

Here is a plunker: http://plnkr.co/edit/rIWYjBZ7vFJzd7fsMHr6?p=preview
How can i get it to work with the Roles service?

**Comment by stumpdk** [comment]
As far as I can see, you are not using the newest version of the code.
The latest commits should make the directive able to handle promises properly.

**Comment by alalonde** [comment]
The problem is in the `$scope.user.roles` definition.  You are referencing `$scope.roles` as if it's an array, but really it's a promise, so `roles[0]` is undefined at the time that the directive is initialized.
